{{- if and (not .Values.beaconChainRpcEndpoints) (not .Values.beaconChainRpcEndpointsRandomized) }}
{{- fail ".Values.beaconChainRpcEndpoints is empty" }}
{{- end }}

{{- if not .Values.suggestedFeeRecipient }}
{{- fail ".Values.suggestedFeeRecipient is empty" }}
{{- end }}

{{- if and .Values.keyManagerApi.enabled .Values.keyManagerApi.tokenSecretName }}
apiVersion: v1
kind: Pod
metadata:
  name: check-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  containers:
  - name: check-secret
    image: busybox
    command: ['sh', '-c']
    args:
      - |
        if [ ! -f /etc/secrets/token ]; then
          echo "Error: Public key {{ .Values.keyManagerApi.tokenSecretPublicKey }} not found!"
          exit 1
        fi

        {{- if .Values.keyManagerApi.tokenSecretPrivateKey }}
        if [ ! -f /etc/secrets/secret ]; then
          echo "Error: Secret key {{ .Values.keyManagerApi.tokenSecretPrivateKey }} not found!"
          exit 1
        fi
        {{- end }}

    volumeMounts:
    {{- if .Values.keyManagerApi.tokenSecretPrivateKey }}
    - name: secret-volume
      mountPath: /etc/secrets/secret
      subPath: {{ .Values.keyManagerApi.tokenSecretPrivateKey }}
      readOnly: true
    {{- end }}
    - name: secret-volume
      mountPath: /etc/secrets/token
      subPath: {{ .Values.keyManagerApi.tokenSecretPublicKey }}
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: {{ .Values.keyManagerApi.tokenSecretName }}
{{- end}}
