{{- if and (not .Values.beaconChainRpcEndpoints) (not .Values.beaconChainRpcEndpointsRandomized) }}
{{- fail ".Values.beaconChainRpcEndpoints is empty" }}
{{- end }}

{{- if not .Values.suggestedFeeRecipient }}
{{- fail ".Values.suggestedFeeRecipient is empty" }}
{{- end }}

{{- if and .Values.keyManagerApi.enabled .Values.keyManagerApi.tokenSecretName }}
apiVersion: v1
kind: Pod
metadata:
  name: check-token-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  restartPolicy: Never
  containers:
  - name: check-secret
    image: busybox
    command: ['sh', '-c']
    args:
      - |
        if [ ! -f /etc/secrets/token ]; then
          echo "Error: Secret token file not found!"
          exit 1
        fi

        secret=$(cat /etc/secrets/token }})

        if [ ${#secret} -lt 16 ]; then
          echo "Error: Secret token must be at least 16 characters long"
          exit 1
        fi

        if ! echo "$secret" | grep -Eq '^[A-Za-z0-9+/=]+$'; then
          echo "Error: Secret token contains invalid characters"
          exit 1
        fi

        echo "Secret token is valid"
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secrets/token
      subPath: {{ .Values.keyManagerApi.tokenSecretKey }}
      readOnly: true
  volumes:
  - name: secret-volume
    secret:
      secretName: {{ .Values.keyManagerApi.tokenSecretName }}
{{- end}}
