apiVersion: v2
name: prysm
version: 4.0.11
appVersion: v4.2.1
kubeVersion: "^1.18.0-0"
description: Go implementation of Ethereum proof of stake.
type: application
keywords:
  - ethereum
  - blockchain
  - prysm
  - p2p
home: https://www.ethereum.org/
sources:
  - https://github.com/prysmaticlabs/prysm
icon: https://raw.githubusercontent.com/ethereum/ethereum-org/master/public/images/logos/ETHEREUM-ICON_Black.png

dependencies:
- name: common
  repository: file://../common
  version: 1.x.x
